### ISSUE TITLE
Graph implementation from Scratch

### ISSUE THREAD

**Issue by Kennedylelei** [muregii/codeKenya#41]
public class Graphs{

    private class Node {
        private String label;

        public Node(String label) {
            this.label = label;
        }

        @Override
        public String toString(){
            return label;
        }

    }

    private Map<String, Node> nodes = new HashMap<>();
    private Map<Node, List<Node>> adjacencyList = new HashMap<>();
       

        public void addNode(String label){
            var node =  new Node(label);
            nodes.putIfAbsent(label, node);
             adjacencyList.putIfAbsent(node, new ArrayList<>());
        
        }

        public void addEdge(String from, String to){
            var fromNode = nodes.get(from);
            if(fromNode == null)
                throw new IllegalArgumentException();

            var toNode = nodes.get(to);
            if(toNode == null)
                throw new IllegalArgumentException();

            adjacencyList.get(fromNode).add(toNode);

        }

        public void print(){
            for(var source : adjacencyList.keySet()) {
                var targets = adjacencyList.get(source);

                if(!targets.isEmpty())
                System.out.println(source +  " is connected to " + targets);
            }
        }

**Comment by muregii** [comment]
I'll look at it.

**Comment by muregii** [comment]
The Implementation seems to use two HashMaps, one with string and nodes, possibly the "Nodes" themselves. 
While the other , a Node and a list of other nodes, this is most likely the Linked List.

private Map<String, Node> nodes = new HashMap<>();
private Map<Node, List<Node>> adjacencyList = new HashMap<>();
